#!/bin/bash

# Update Stripe Price IDs in .env
sed -i 's/STRIPE_STARTER_PRICE_ID=.*/STRIPE_STARTER_PRICE_ID=price_1SMslsFIOSLx4Sb7eso0oBNt/' .env
sed -i 's/STRIPE_PRO_PRICE_ID=.*/STRIPE_PRO_PRICE_ID=price_1SMsmWFIOSLx4Sb7nGdwNXzS/' .env
sed -i 's/STRIPE_BUSINESS_PRICE_ID=.*/STRIPE_BUSINESS_PRICE_ID=price_1SMsnEFIOSLx4Sb7LZyl1q33/' .env
sed -i 's/NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID=.*/NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID=price_1SMslsFIOSLx4Sb7eso0oBNt/' .env
sed -i 's/NEXT_PUBLIC_STRIPE_PRO_PRICE_ID=.*/NEXT_PUBLIC_STRIPE_PRO_PRICE_ID=price_1SMsmWFIOSLx4Sb7nGdwNXzS/' .env
sed -i 's/NEXT_PUBLIC_STRIPE_BUSINESS_PRICE_ID=.*/NEXT_PUBLIC_STRIPE_BUSINESS_PRICE_ID=price_1SMsnEFIOSLx4Sb7LZyl1q33/' .env

echo "Stripe Price IDs updated successfully!"
