import { createClient } from '@/lib/supabase-server';
import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// GET /api/blog/posts - List posts with filtering, pagination, sorting
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    
    // Pagination
    const page = parseInt(searchParams.get('page') || '1');
    const perPage = parseInt(searchParams.get('per_page') || '10');
    const offset = (page - 1) * perPage;
    
    // Filters
    const status = searchParams.get('status');
    const category = searchParams.get('category');
    const tag = searchParams.get('tag');
    const author = searchParams.get('author');
    const search = searchParams.get('search');
    
    // Sorting
    const sortBy = searchParams.get('sort_by') || 'published_at';
    const sortOrder = searchParams.get('sort_order') || 'desc';

    const supabase = createClient();

    // Build query
    let query = supabase
      .from('articles')
      .select(`
        *,
        author:author_id(id, email),
        categories:article_category_mapping(category:article_categories(*)),
        tags:article_tag_mapping(tag:article_tags(*))
      `, { count: 'exact' });

    // Apply filters
    if (status) {
      query = query.eq('status', status);
    }
    
    if (author) {
      query = query.eq('author_id', author);
    }

    if (search) {
      query = query.or(`title.ilike.%${search}%,content.ilike.%${search}%,excerpt.ilike.%${search}%`);
    }

    // Category and tag filtering would need joins, simplified here
    if (category) {
      // This requires a more complex query with joins
      const { data: categoryData } = await supabase
        .from('article_categories')
        .select('id')
        .eq('slug', category)
        .single();
      
      if (categoryData) {
        const { data: postIds } = await supabase
          .from('article_category_mapping')
          .select('article_id')
          .eq('category_id', categoryData.id);
        
        if (postIds && postIds.length > 0) {
          query = query.in('id', postIds.map(p => p.article_id));
        }
      }
    }

    if (tag) {
      const { data: tagData } = await supabase
        .from('article_tags')
        .select('id')
        .eq('slug', tag)
        .single();
      
      if (tagData) {
        const { data: postIds } = await supabase
          .from('article_tag_mapping')
          .select('article_id')
          .eq('tag_id', tagData.id);
        
        if (postIds && postIds.length > 0) {
          query = query.in('id', postIds.map(p => p.article_id));
        }
      }
    }

    // Apply sorting
    query = query.order(sortBy, { ascending: sortOrder === 'asc' });

    // Apply pagination
    query = query.range(offset, offset + perPage - 1);

    const { data: posts, error, count } = await query;

    if (error) {
      console.error('Error fetching posts:', error);
      return NextResponse.json({ error: 'Failed to fetch posts' }, { status: 500 });
    }

    return NextResponse.json({
      posts,
      pagination: {
        page,
        per_page: perPage,
        total: count || 0,
        total_pages: Math.ceil((count || 0) / perPage)
      }
    });
  } catch (error) {
    console.error('Error in GET /api/blog/posts:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/blog/posts - Create new post
export async function POST(request: NextRequest) {
  try {
    const supabase = createClient();
    
    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      title,
      slug,
      content,
      excerpt,
      featured_image,
      status,
      published_at,
      meta_title,
      meta_description,
      focus_keyword,
      seo_keywords,
      categories,
      tags
    } = body;

    // Validate required fields
    if (!title || !content) {
      return NextResponse.json(
        { error: 'Title and content are required' },
        { status: 400 }
      );
    }

    // Create post
    const { data: post, error: postError } = await supabase
      .from('articles')
      .insert({
        title,
        slug: slug || null, // Will be auto-generated by trigger if not provided
        content,
        excerpt,
        featured_image,
        status: status || 'draft',
        published_at: status === 'published' ? (published_at || new Date().toISOString()) : published_at,
        meta_title,
        meta_description,
        focus_keyword,
        seo_keywords,
        author_id: user.id
      })
      .select()
      .single();

    if (postError) {
      console.error('Error creating post:', postError);
      return NextResponse.json({ error: 'Failed to create post' }, { status: 500 });
    }

    // Add categories
    if (categories && categories.length > 0) {
      const categoryMappings = categories.map((categoryId: string) => ({
        article_id: post.id,
        category_id: categoryId
      }));

      await supabase
        .from('article_category_mapping')
        .insert(categoryMappings);
    }

    // Add tags
    if (tags && tags.length > 0) {
      const tagMappings = tags.map((tagId: string) => ({
        article_id: post.id,
        tag_id: tagId
      }));

      await supabase
        .from('article_tag_mapping')
        .insert(tagMappings);
    }

    return NextResponse.json({ post }, { status: 201 });
  } catch (error) {
    console.error('Error in POST /api/blog/posts:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
