/**
 * Image Model Configuration
 * Maps internal model IDs to AIML API model IDs with metadata
 */

export interface ImageModel {
  id: string;
  name: string;
  provider: string;
  apiModel: string;
  tier: 'budget' | 'standard' | 'premium' | 'ultra';
  credits: number;
  capabilities: {
    textToImage: boolean;
    imageToImage: boolean;
    editing: boolean;
    lora: boolean;
    aspectRatios?: string[];
  };
  description: string;
  apiReference?: string;
}

export const IMAGE_MODELS: Record<string, ImageModel> = {
  // ========== ALIBABA CLOUD ==========
  image_qwen: {
    id: 'image_qwen',
    name: 'Qwen Image',
    provider: 'Alibaba Cloud',
    apiModel: 'alibaba/qwen-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'High-quality image generation from Alibaba Cloud',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/alibaba-qwen-image',
  },
  image_qwen_edit: {
    id: 'image_qwen_edit',
    name: 'Qwen Image Edit',
    provider: 'Alibaba Cloud',
    apiModel: 'alibaba/qwen-image-edit',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Image editing and modification capabilities',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/alibaba-qwen-image-edit',
  },
  image_z_turbo: {
    id: 'image_z_turbo',
    name: 'Z-Image Turbo',
    provider: 'Alibaba Cloud',
    apiModel: 'alibaba/z-image-turbo',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16'],
    },
    description: 'Fast image generation with Alibaba Z-Image',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/alibaba-z-image-turbo',
  },
  image_z_turbo_lora: {
    id: 'image_z_turbo_lora',
    name: 'Z-Image Turbo LoRA',
    provider: 'Alibaba Cloud',
    apiModel: 'alibaba/z-image-turbo-lora',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: true,
    },
    description: 'Z-Image with LoRA fine-tuning support',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/alibaba-z-image-turbo-lora',
  },

  // ========== BYTEDANCE ==========
  image_seedream3: {
    id: 'image_seedream3',
    name: 'Seedream 3.0',
    provider: 'ByteDance',
    apiModel: 'bytedance/seedream-3.0',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'ByteDance Seedream 3.0 text-to-image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/bytedance-seedream-3',
  },
  image_seededit3_i2i: {
    id: 'image_seededit3_i2i',
    name: 'Seededit 3.0 I2I',
    provider: 'ByteDance',
    apiModel: 'bytedance/seededit-3.0-i2i',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Image-to-image transformation with Seedream 3.0',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/bytedance-seededit-3',
  },
  image_seedream4: {
    id: 'image_seedream4',
    name: 'Seedream 4 Text-to-Image',
    provider: 'ByteDance',
    apiModel: 'bytedance/seedream-v4-text-to-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Next-generation Seedream 4 image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/bytedance-seedream-4',
  },
  image_seedream4_edit: {
    id: 'image_seedream4_edit',
    name: 'Seedream 4 Edit',
    provider: 'ByteDance',
    apiModel: 'bytedance/seedream-v4-edit',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Advanced editing with Seedream 4',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/bytedance-seedream-4-edit',
  },
  image_uso: {
    id: 'image_uso',
    name: 'USO',
    provider: 'ByteDance',
    apiModel: 'bytedance/uso',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
    },
    description: 'ByteDance USO specialized image model',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/bytedance-uso',
  },
  image_seedream45: {
    id: 'image_seedream45',
    name: 'Seedream 4.5',
    provider: 'ByteDance',
    apiModel: 'bytedance/seedream-4-5',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    },
    description: 'Latest Seedream 4.5 with enhanced quality',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/bytedance-seedream-45',
  },

  // ========== FLUX (Black Forest Labs) ==========
  image_flux_pro: {
    id: 'image_flux_pro',
    name: 'FLUX.1 [pro]',
    provider: 'Flux',
    apiModel: 'flux-pro',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '9:21'],
    },
    description: 'Professional-grade FLUX.1 image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-pro',
  },
  image_flux_pro_v11: {
    id: 'image_flux_pro_v11',
    name: 'FLUX 1.1 [pro]',
    provider: 'Flux',
    apiModel: 'flux-pro/v1.1',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '9:21'],
    },
    description: 'Enhanced FLUX 1.1 Pro with improved quality',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-pro-v11',
  },
  image_flux_pro_ultra: {
    id: 'image_flux_pro_ultra',
    name: 'FLUX 1.1 [pro ultra]',
    provider: 'Flux',
    apiModel: 'flux-pro/v1.1-ultra',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '9:21'],
    },
    description: 'Ultra high-quality FLUX 1.1 Pro',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-pro-ultra',
  },
  image_flux_realism: {
    id: 'image_flux_realism',
    name: 'FLUX Realism LoRA',
    provider: 'Flux',
    apiModel: 'flux-realism',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: true,
    },
    description: 'Photorealistic images with FLUX Realism LoRA',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-realism',
  },
  image_flux_dev: {
    id: 'image_flux_dev',
    name: 'FLUX.1 [dev]',
    provider: 'Flux',
    apiModel: 'flux/dev',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Development version of FLUX.1',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-dev',
  },
  image_flux_dev_i2i: {
    id: 'image_flux_dev_i2i',
    name: 'FLUX.1 [dev] I2I',
    provider: 'Flux',
    apiModel: 'flux/dev/image-to-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: false,
      lora: false,
    },
    description: 'Image-to-image with FLUX.1 Dev',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-dev-i2i',
  },
  image_flux_schnell: {
    id: 'image_flux_schnell',
    name: 'FLUX.1 [schnell]',
    provider: 'Flux',
    apiModel: 'flux/schnell',
    tier: 'budget',
    credits: 1,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16'],
    },
    description: 'Fast FLUX.1 generation (schnell = fast in German)',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-schnell',
  },
  image_flux_kontext_max: {
    id: 'image_flux_kontext_max',
    name: 'FLUX.1 Kontext [max]',
    provider: 'Flux',
    apiModel: 'flux/kontext-max/text-to-image',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Maximum context understanding with FLUX Kontext',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-kontext-max',
  },
  image_flux_kontext_max_i2i: {
    id: 'image_flux_kontext_max_i2i',
    name: 'FLUX.1 Kontext [max] I2I',
    provider: 'Flux',
    apiModel: 'flux/kontext-max/image-to-image',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: false,
      lora: false,
    },
    description: 'Image-to-image with FLUX Kontext Max',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-kontext-max-i2i',
  },
  image_flux_kontext_pro: {
    id: 'image_flux_kontext_pro',
    name: 'FLUX.1 Kontext [pro]',
    provider: 'Flux',
    apiModel: 'flux/kontext-pro/text-to-image',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Professional context-aware image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-kontext-pro',
  },
  image_flux_kontext_pro_i2i: {
    id: 'image_flux_kontext_pro_i2i',
    name: 'FLUX.1 Kontext [pro] I2I',
    provider: 'Flux',
    apiModel: 'flux/kontext-pro/image-to-image',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: false,
      lora: false,
    },
    description: 'Image-to-image with FLUX Kontext Pro',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-kontext-pro-i2i',
  },
  image_flux_srpo: {
    id: 'image_flux_srpo',
    name: 'FLUX.1 SRPO',
    provider: 'Flux',
    apiModel: 'flux/srpo',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'FLUX with Super-Resolution Post-processing',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-srpo',
  },
  image_flux_srpo_i2i: {
    id: 'image_flux_srpo_i2i',
    name: 'FLUX.1 SRPO I2I',
    provider: 'Flux',
    apiModel: 'flux/srpo/image-to-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: false,
      lora: false,
    },
    description: 'Image-to-image with Super-Resolution',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-srpo-i2i',
  },
  image_flux2: {
    id: 'image_flux2',
    name: 'FLUX.2',
    provider: 'Flux',
    apiModel: 'blackforestlabs/flux-2',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '9:21'],
    },
    description: 'Next-generation FLUX.2 image model',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-2',
  },
  image_flux2_edit: {
    id: 'image_flux2_edit',
    name: 'FLUX.2 Edit',
    provider: 'Flux',
    apiModel: 'blackforestlabs/flux-2-edit',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Advanced editing with FLUX.2',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-2-edit',
  },
  image_flux2_lora: {
    id: 'image_flux2_lora',
    name: 'FLUX.2 LoRA',
    provider: 'Flux',
    apiModel: 'blackforestlabs/flux-2-lora',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: true,
    },
    description: 'FLUX.2 with LoRA fine-tuning support',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-2-lora',
  },
  image_flux2_lora_edit: {
    id: 'image_flux2_lora_edit',
    name: 'FLUX.2 LoRA Edit',
    provider: 'Flux',
    apiModel: 'blackforestlabs/flux-2-lora-edit',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: true,
    },
    description: 'Image editing with FLUX.2 LoRA',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-2-lora-edit',
  },
  image_flux2_pro: {
    id: 'image_flux2_pro',
    name: 'FLUX.2 [pro]',
    provider: 'Flux',
    apiModel: 'blackforestlabs/flux-2-pro',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '9:21'],
    },
    description: 'Professional FLUX.2 with enhanced capabilities',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-2-pro',
  },
  image_flux2_pro_edit: {
    id: 'image_flux2_pro_edit',
    name: 'FLUX.2 [pro] Edit',
    provider: 'Flux',
    apiModel: 'blackforestlabs/flux-2-pro-edit',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Professional editing with FLUX.2 Pro',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/flux-2-pro-edit',
  },

  // ========== GOOGLE ==========
  image_imagen3: {
    id: 'image_imagen3',
    name: 'Imagen 3',
    provider: 'Google',
    apiModel: 'imagen-3.0-generate-002',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Google Imagen 3 text-to-image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-imagen-3',
  },
  image_imagen4: {
    id: 'image_imagen4',
    name: 'Imagen 4.0',
    provider: 'Google',
    apiModel: 'google/imagen-4.0-generate-001',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Google Imagen 4 with improved quality',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-imagen-4',
  },
  image_imagen4_fast: {
    id: 'image_imagen4_fast',
    name: 'Imagen 4.0 Fast',
    provider: 'Google',
    apiModel: 'google/imagen-4.0-fast-generate-001',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16'],
    },
    description: 'Faster Imagen 4 generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-imagen-4-fast',
  },
  image_imagen4_ultra: {
    id: 'image_imagen4_ultra',
    name: 'Imagen 4 Ultra',
    provider: 'Google',
    apiModel: 'google/imagen-4.0-ultra-generate-001',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Ultra high-quality Imagen 4',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-imagen-4-ultra',
  },
  image_gemini_flash: {
    id: 'image_gemini_flash',
    name: 'Gemini 2.5 Flash Image',
    provider: 'Google',
    apiModel: 'google/gemini-2.5-flash-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Fast image generation with Gemini 2.5 Flash',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-gemini-flash-image',
  },
  image_gemini_flash_edit: {
    id: 'image_gemini_flash_edit',
    name: 'Gemini 2.5 Flash Image Edit',
    provider: 'Google',
    apiModel: 'google/gemini-2.5-flash-image-edit',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Image editing with Gemini 2.5 Flash',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-gemini-flash-edit',
  },
  image_gemini3_pro: {
    id: 'image_gemini3_pro',
    name: 'Gemini 3 Pro Image',
    provider: 'Google',
    apiModel: 'google/gemini-3-pro-image-preview',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Professional image generation with Gemini 3 Pro',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-gemini-3-pro',
  },
  image_gemini3_edit: {
    id: 'image_gemini3_edit',
    name: 'Gemini 3 Pro Image Edit',
    provider: 'Google',
    apiModel: 'google/gemini-3-pro-image-preview-edit',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Advanced editing with Gemini 3 Pro',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/google-gemini-3-edit',
  },

  // ========== KLING AI ==========
  image_kling_o1: {
    id: 'image_kling_o1',
    name: 'Kling Image O1',
    provider: 'Kling AI',
    apiModel: 'klingai/image-o1',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Advanced image generation with Kling O1',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/kling-o1',
  },

  // ========== OPENAI ==========
  image_dalle2: {
    id: 'image_dalle2',
    name: 'DALL·E 2',
    provider: 'OpenAI',
    apiModel: 'dall-e-2',
    tier: 'budget',
    credits: 1,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1'],
    },
    description: 'OpenAI DALL·E 2 image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/openai-dalle-2',
  },
  image_dalle3: {
    id: 'image_dalle3',
    name: 'DALL·E 3',
    provider: 'OpenAI',
    apiModel: 'dall-e-3',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16'],
    },
    description: 'OpenAI DALL·E 3 with improved quality',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/openai-dalle-3',
  },
  image_gpt_image1: {
    id: 'image_gpt_image1',
    name: 'GPT Image 1',
    provider: 'OpenAI',
    apiModel: 'openai/gpt-image-1',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'OpenAI GPT Image 1 generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/openai-gpt-image-1',
  },
  image_gpt_image15: {
    id: 'image_gpt_image15',
    name: 'GPT Image 1.5',
    provider: 'OpenAI',
    apiModel: 'openai/gpt-image-1-5',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'OpenAI GPT Image 1.5 with enhanced capabilities',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/openai-gpt-image-15',
  },

  // ========== RECRAFT AI ==========
  image_recraft_v3: {
    id: 'image_recraft_v3',
    name: 'Recraft v3',
    provider: 'Recraft AI',
    apiModel: 'recraft-v3',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Recraft v3 image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/recraft-v3',
  },

  // ========== REVE ==========
  image_reve_create: {
    id: 'image_reve_create',
    name: 'Reve Create Image',
    provider: 'Reve',
    apiModel: 'reve/create-image',
    tier: 'budget',
    credits: 1,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16'],
    },
    description: 'Reve image creation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/reve-create',
  },
  image_reve_edit: {
    id: 'image_reve_edit',
    name: 'Reve Edit Image',
    provider: 'Reve',
    apiModel: 'reve/edit-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Reve image editing',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/reve-edit',
  },
  image_reve_remix: {
    id: 'image_reve_remix',
    name: 'Reve Remix Image',
    provider: 'Reve',
    apiModel: 'reve/remix-edit-image',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Reve image remixing and transformation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/reve-remix',
  },

  // ========== STABILITY AI ==========
  image_sd3_medium: {
    id: 'image_sd3_medium',
    name: 'Stable Diffusion 3',
    provider: 'Stability AI',
    apiModel: 'stable-diffusion-v3-medium',
    tier: 'budget',
    credits: 1,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Stable Diffusion 3 medium model',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/sd3-medium',
  },
  image_sd35_large: {
    id: 'image_sd35_large',
    name: 'Stable Diffusion 3.5 Large',
    provider: 'Stability AI',
    apiModel: 'stable-diffusion-v35-large',
    tier: 'premium',
    credits: 3,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Stable Diffusion 3.5 large model',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/sd35-large',
  },

  // ========== TENCENT ==========
  image_hunyuan3: {
    id: 'image_hunyuan3',
    name: 'HunyuanImage 3.0',
    provider: 'Tencent',
    apiModel: 'hunyuan/hunyuan-image-v3-text-to-image',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'Tencent HunyuanImage 3.0',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/hunyuan-3',
  },

  // ========== TOPAZ LABS ==========
  image_topaz_sharpen: {
    id: 'image_topaz_sharpen',
    name: 'Topaz Sharpen',
    provider: 'Topaz Labs',
    apiModel: 'topaz-labs/sharpen',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'AI-powered image sharpening',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/topaz-sharpen',
  },
  image_topaz_sharpen_gen: {
    id: 'image_topaz_sharpen_gen',
    name: 'Topaz Sharpen Generative',
    provider: 'Topaz Labs',
    apiModel: 'topaz-labs/sharpen-gen',
    tier: 'standard',
    credits: 2,
    capabilities: {
      textToImage: false,
      imageToImage: true,
      editing: true,
      lora: false,
    },
    description: 'Generative AI sharpening with detail enhancement',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/topaz-sharpen-gen',
  },

  // ========== XAI ==========
  image_grok2: {
    id: 'image_grok2',
    name: 'Grok 2 Image',
    provider: 'xAI',
    apiModel: 'x-ai/grok-2-image',
    tier: 'ultra',
    credits: 4,
    capabilities: {
      textToImage: true,
      imageToImage: false,
      editing: false,
      lora: false,
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    },
    description: 'xAI Grok 2 image generation',
    apiReference: 'https://docs.aimlapi.com/api-reference/image-generation/grok-2-image',
  },
};

/**
 * Get models by tier
 */
export function getModelsByTier(tier: 'budget' | 'standard' | 'premium' | 'ultra'): ImageModel[] {
  return Object.values(IMAGE_MODELS).filter(model => model.tier === tier);
}

/**
 * Get models by capability
 */
export function getModelsByCapability(capability: 'textToImage' | 'imageToImage' | 'editing' | 'lora'): ImageModel[] {
  return Object.values(IMAGE_MODELS).filter(model => model.capabilities[capability]);
}

/**
 * Get model by ID
 */
export function getModelById(id: string): ImageModel | undefined {
  return IMAGE_MODELS[id];
}

/**
 * Get all models
 */
export function getAllModels(): ImageModel[] {
  return Object.values(IMAGE_MODELS);
}

/**
 * Get models by provider
 */
export function getModelsByProvider(provider: string): ImageModel[] {
  return Object.values(IMAGE_MODELS).filter(model => model.provider === provider);
}
