
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/db';

/**
 * GET /api/auto-content/topics
 * Get all auto-generated topics for the logged-in client
 */
export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const client = await prisma.client.findUnique({
      where: { email: session.user.email },
    });

    if (!client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }

    const strategy = await prisma.autoContentStrategy.findUnique({
      where: { clientId: client.id },
    });

    if (!strategy) {
      return NextResponse.json([]);
    }

    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const limit = parseInt(searchParams.get('limit') || '50');

    const where: any = {
      strategyId: strategy.id,
    };

    if (status) {
      where.status = status;
    }

    const topics = await prisma.autoGeneratedTopic.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: limit,
    });

    return NextResponse.json(topics);
  } catch (error) {
    console.error('Error fetching topics:', error);
    return NextResponse.json(
      { error: 'Failed to fetch topics' },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/auto-content/topics
 * Delete a specific topic or all topics
 */
export async function DELETE(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const client = await prisma.client.findUnique({
      where: { email: session.user.email },
    });

    if (!client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }

    const { searchParams } = new URL(request.url);
    const topicId = searchParams.get('id');

    if (topicId) {
      // Delete specific topic
      await prisma.autoGeneratedTopic.delete({
        where: { id: topicId },
      });
    } else {
      // Delete all topics for this client's strategy
      const strategy = await prisma.autoContentStrategy.findUnique({
        where: { clientId: client.id },
      });

      if (strategy) {
        await prisma.autoGeneratedTopic.deleteMany({
          where: { strategyId: strategy.id },
        });
      }
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting topics:', error);
    return NextResponse.json(
      { error: 'Failed to delete topics' },
      { status: 500 }
    );
  }
}
