
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ArrowLeft, Sparkles, Loader2, Zap, Check, X, Calendar, TrendingUp, Eye } from 'lucide-react';
import toast from 'react-hot-toast';

interface AutoContentStrategy {
  id: string;
  niche: string;
  subTopics: string[];
  targetAudience?: string;
  isEnabled: boolean;
  postsPerDay: number;
  preferredPostTime: string;
  contentTypes: string[];
  toneOfVoice: string;
  language: string;
  useAITopicGeneration: boolean;
  autoPublish: boolean;
  totalGenerated: number;
  totalPublished: number;
  lastGeneratedAt?: string;
  GeneratedTopics?: AutoGeneratedTopic[];
}

interface AutoGeneratedTopic {
  id: string;
  topic: string;
  description?: string;
  keywords: string[];
  contentType: string;
  status: string;
  scheduledFor?: string;
  createdAt: string;
}

export default function AutoContentPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [strategy, setStrategy] = useState<AutoContentStrategy | null>(null);
  const [topics, setTopics] = useState<AutoGeneratedTopic[]>([]);
  
  const [formData, setFormData] = useState({
    niche: '',
    subTopics: '',
    targetAudience: '',
    isEnabled: true,
    postsPerDay: 1,
    preferredPostTime: '09:00',
    contentTypes: ['article'],
    toneOfVoice: 'professional',
    language: 'Dutch',
    useAITopicGeneration: true,
    autoPublish: false,
  });

  useEffect(() => {
    fetchStrategy();
  }, []);

  const fetchStrategy = async () => {
    try {
      const response = await fetch('/api/auto-content/strategy');
      if (response.ok) {
        const data = await response.json();
        if (data) {
          setStrategy(data);
          setFormData({
            niche: data.niche,
            subTopics: data.subTopics.join(', '),
            targetAudience: data.targetAudience || '',
            isEnabled: data.isEnabled,
            postsPerDay: data.postsPerDay,
            preferredPostTime: data.preferredPostTime,
            contentTypes: data.contentTypes,
            toneOfVoice: data.toneOfVoice,
            language: data.language,
            useAITopicGeneration: data.useAITopicGeneration,
            autoPublish: data.autoPublish,
          });
          setTopics(data.GeneratedTopics || []);
        }
      }
    } catch (error) {
      console.error('Error fetching strategy:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSaveStrategy = async () => {
    if (!formData.niche) {
      toast.error('Vul minimaal een niche in');
      return;
    }

    setSaving(true);
    try {
      const response = await fetch('/api/auto-content/strategy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...formData,
          subTopics: formData.subTopics
            .split(',')
            .map((t) => t.trim())
            .filter((t) => t),
        }),
      });

      if (response.ok) {
        toast.success('Strategie opgeslagen!');
        fetchStrategy();
      } else {
        toast.error('Kon strategie niet opslaan');
      }
    } catch (error) {
      console.error('Error saving strategy:', error);
      toast.error('Er ging iets mis');
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateTopics = async (count: number = 30) => {
    if (!strategy) {
      toast.error('Sla eerst je strategie op');
      return;
    }

    setGenerating(true);
    try {
      const response = await fetch('/api/auto-content/generate-topics', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          niche: strategy.niche,
          count,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        toast.success(`${data.count} onderwerpen gegenereerd!`);
        fetchStrategy();
      } else {
        const error = await response.json();
        toast.error(error.error || 'Kon onderwerpen niet genereren');
      }
    } catch (error) {
      console.error('Error generating topics:', error);
      toast.error('Er ging iets mis');
    } finally {
      setGenerating(false);
    }
  };

  const handleContentTypeToggle = (type: string) => {
    const newTypes = formData.contentTypes.includes(type)
      ? formData.contentTypes.filter((t) => t !== type)
      : [...formData.contentTypes, type];
    setFormData({ ...formData, contentTypes: newTypes });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-blue-50 p-6 flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-orange-600" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-blue-50 p-6">
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Header */}
        <div>
          <Button
            variant="ghost"
            onClick={() => router.push('/client-portal')}
            className="mb-4"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Terug naar Dashboard
          </Button>
          <h1 className="text-4xl font-bold bg-gradient-to-r from-orange-600 to-orange-500 bg-clip-text text-transparent">
            Auto Content Planner
          </h1>
          <p className="text-gray-600 mt-2">
            Vul je niche in en laat AI automatisch onderwerpen bedenken en dagelijks content genereren
          </p>
        </div>

        {/* Stats Cards */}
        {strategy && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-gray-600">Status</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2">
                  <Badge
                    variant={strategy.isEnabled ? 'default' : 'secondary'}
                    className={
                      strategy.isEnabled
                        ? 'bg-green-500 hover:bg-green-600'
                        : ''
                    }
                  >
                    {strategy.isEnabled ? (
                      <>
                        <Zap className="h-3 w-3 mr-1" />
                        Actief
                      </>
                    ) : (
                      'Gepauzeerd'
                    )}
                  </Badge>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-gray-600">
                  Gegenereerd
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-bold text-gray-900">
                    {strategy.totalGenerated}
                  </span>
                  <span className="text-sm text-gray-500">onderwerpen</span>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-gray-600">
                  Gepubliceerd
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-bold text-gray-900">
                    {strategy.totalPublished}
                  </span>
                  <span className="text-sm text-gray-500">artikelen</span>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Strategy Configuration */}
        <Card>
          <CardHeader>
            <CardTitle>Content Strategie</CardTitle>
            <CardDescription>
              Configureer je automatische content generatie
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Niche */}
            <div className="space-y-2">
              <Label htmlFor="niche">Niche / Hoofdonderwerp *</Label>
              <Input
                id="niche"
                value={formData.niche}
                onChange={(e) => setFormData({ ...formData, niche: e.target.value })}
                placeholder="Bijv: Digital Marketing, Gezonde voeding, Persoonlijke ontwikkeling"
              />
              <p className="text-xs text-gray-500">
                Het hoofdthema waarover je content wilt creëren
              </p>
            </div>

            {/* Sub Topics */}
            <div className="space-y-2">
              <Label htmlFor="subTopics">Sub-onderwerpen (optioneel)</Label>
              <Textarea
                id="subTopics"
                value={formData.subTopics}
                onChange={(e) => setFormData({ ...formData, subTopics: e.target.value })}
                placeholder="Bijv: SEO, Content Marketing, Social Media (gescheiden door komma's)"
                rows={3}
              />
              <p className="text-xs text-gray-500">
                Specifieke sub-topics waar AI rekening mee houdt bij het genereren
              </p>
            </div>

            {/* Target Audience */}
            <div className="space-y-2">
              <Label htmlFor="targetAudience">Doelgroep</Label>
              <Input
                id="targetAudience"
                value={formData.targetAudience}
                onChange={(e) =>
                  setFormData({ ...formData, targetAudience: e.target.value })
                }
                placeholder="Bijv: Ondernemers, Studenten, Ouders"
              />
            </div>

            <Separator />

            {/* Settings Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Posts Per Day */}
              <div className="space-y-2">
                <Label htmlFor="postsPerDay">Posts per dag</Label>
                <Input
                  id="postsPerDay"
                  type="number"
                  min="1"
                  max="10"
                  value={formData.postsPerDay}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      postsPerDay: parseInt(e.target.value) || 1,
                    })
                  }
                />
              </div>

              {/* Preferred Time */}
              <div className="space-y-2">
                <Label htmlFor="preferredPostTime">Voorkeurstijd</Label>
                <Input
                  id="preferredPostTime"
                  type="time"
                  value={formData.preferredPostTime}
                  onChange={(e) =>
                    setFormData({ ...formData, preferredPostTime: e.target.value })
                  }
                />
              </div>

              {/* Tone of Voice */}
              <div className="space-y-2">
                <Label htmlFor="toneOfVoice">Tone of Voice</Label>
                <Select
                  value={formData.toneOfVoice}
                  onValueChange={(value) =>
                    setFormData({ ...formData, toneOfVoice: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="professional">Professioneel</SelectItem>
                    <SelectItem value="casual">Casual</SelectItem>
                    <SelectItem value="friendly">Vriendelijk</SelectItem>
                    <SelectItem value="authoritative">Gezaghebbend</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Language */}
              <div className="space-y-2">
                <Label htmlFor="language">Taal</Label>
                <Select
                  value={formData.language}
                  onValueChange={(value) =>
                    setFormData({ ...formData, language: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Dutch">Nederlands</SelectItem>
                    <SelectItem value="English">Engels</SelectItem>
                    <SelectItem value="German">Duits</SelectItem>
                    <SelectItem value="French">Frans</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <Separator />

            {/* Content Types */}
            <div className="space-y-2">
              <Label>Content Types</Label>
              <div className="flex flex-wrap gap-3">
                <Button
                  type="button"
                  variant={
                    formData.contentTypes.includes('article') ? 'default' : 'outline'
                  }
                  onClick={() => handleContentTypeToggle('article')}
                  className="flex items-center gap-2"
                >
                  {formData.contentTypes.includes('article') ? (
                    <Check className="h-4 w-4" />
                  ) : (
                    <X className="h-4 w-4" />
                  )}
                  Artikelen
                </Button>
                <Button
                  type="button"
                  variant={
                    formData.contentTypes.includes('social-post')
                      ? 'default'
                      : 'outline'
                  }
                  onClick={() => handleContentTypeToggle('social-post')}
                  className="flex items-center gap-2"
                >
                  {formData.contentTypes.includes('social-post') ? (
                    <Check className="h-4 w-4" />
                  ) : (
                    <X className="h-4 w-4" />
                  )}
                  Social Posts
                </Button>
                <Button
                  type="button"
                  variant={
                    formData.contentTypes.includes('video') ? 'default' : 'outline'
                  }
                  onClick={() => handleContentTypeToggle('video')}
                  className="flex items-center gap-2"
                >
                  {formData.contentTypes.includes('video') ? (
                    <Check className="h-4 w-4" />
                  ) : (
                    <X className="h-4 w-4" />
                  )}
                  Video's
                </Button>
              </div>
            </div>

            <Separator />

            {/* Toggles */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label htmlFor="isEnabled">Automatisering inschakelen</Label>
                  <p className="text-xs text-gray-500">
                    Start automatische content generatie
                  </p>
                </div>
                <Switch
                  id="isEnabled"
                  checked={formData.isEnabled}
                  onCheckedChange={(checked) =>
                    setFormData({ ...formData, isEnabled: checked })
                  }
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label htmlFor="useAITopicGeneration">AI Topic Generatie</Label>
                  <p className="text-xs text-gray-500">
                    Laat AI automatisch nieuwe onderwerpen bedenken
                  </p>
                </div>
                <Switch
                  id="useAITopicGeneration"
                  checked={formData.useAITopicGeneration}
                  onCheckedChange={(checked) =>
                    setFormData({ ...formData, useAITopicGeneration: checked })
                  }
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label htmlFor="autoPublish">Auto Publiceren</Label>
                  <p className="text-xs text-gray-500">
                    Publiceer automatisch zonder review (aanbevolen: uit)
                  </p>
                </div>
                <Switch
                  id="autoPublish"
                  checked={formData.autoPublish}
                  onCheckedChange={(checked) =>
                    setFormData({ ...formData, autoPublish: checked })
                  }
                />
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3 pt-4">
              <Button
                onClick={handleSaveStrategy}
                disabled={saving}
                className="bg-gradient-to-r from-orange-600 to-orange-500 hover:from-orange-700 hover:to-orange-600"
              >
                {saving ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Bezig met opslaan...
                  </>
                ) : (
                  <>
                    <Check className="mr-2 h-4 w-4" />
                    Strategie Opslaan
                  </>
                )}
              </Button>

              {strategy && (
                <Button
                  onClick={() => handleGenerateTopics(30)}
                  disabled={generating}
                  variant="outline"
                >
                  {generating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Genereren...
                    </>
                  ) : (
                    <>
                      <Sparkles className="mr-2 h-4 w-4" />
                      30 Onderwerpen Genereren
                    </>
                  )}
                </Button>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Generated Topics */}
        {topics.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Gegenereerde Onderwerpen</CardTitle>
              <CardDescription>
                AI-gegenereerde content onderwerpen gebaseerd op je niche
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {topics.slice(0, 10).map((topic) => (
                  <div
                    key={topic.id}
                    className="flex items-start gap-4 p-4 border rounded-lg hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex-1">
                      <h3 className="font-semibold text-gray-900">{topic.topic}</h3>
                      {topic.description && (
                        <p className="text-sm text-gray-600 mt-1">
                          {topic.description}
                        </p>
                      )}
                      {topic.keywords.length > 0 && (
                        <div className="flex gap-2 mt-2">
                          {topic.keywords.slice(0, 3).map((keyword, idx) => (
                            <Badge key={idx} variant="secondary" className="text-xs">
                              {keyword}
                            </Badge>
                          ))}
                        </div>
                      )}
                    </div>
                    <Badge
                      variant={topic.status === 'PUBLISHED' ? 'default' : 'secondary'}
                    >
                      {topic.status}
                    </Badge>
                  </div>
                ))}
                {topics.length > 10 && (
                  <div className="text-center text-sm text-gray-500">
                    En nog {topics.length - 10} onderwerpen meer...
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
