-- ============================================
-- Add contentPlan column to Project table
-- ============================================

-- Add contentPlan JSONB column
ALTER TABLE "Project" 
ADD COLUMN IF NOT EXISTS "contentPlan" JSONB DEFAULT '[]'::jsonb;

-- Add index for better query performance
CREATE INDEX IF NOT EXISTS "Project_contentPlan_idx" 
ON "Project" USING gin ("contentPlan");

-- Add comment for documentation
COMMENT ON COLUMN "Project"."contentPlan" 
IS 'Array of content plan topics generated by AI. Each topic has: title, description, keywords, priority';

-- Verify column was added
SELECT column_name, data_type, column_default
FROM information_schema.columns 
WHERE table_name = 'Project' AND column_name = 'contentPlan';
