-- ============================================
-- ROBUST Content Plan Column Migration
-- Date: 2025-12-15
-- Purpose: Add contentPlan JSONB column with full error handling
-- ============================================

-- Step 1: Check if column exists, if not add it
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'Project' 
          AND column_name = 'contentPlan'
    ) THEN
        -- Add contentPlan JSONB column
        ALTER TABLE "Project" 
        ADD COLUMN "contentPlan" JSONB DEFAULT '[]'::jsonb;
        
        RAISE NOTICE '✅ Column contentPlan added successfully';
    ELSE
        RAISE NOTICE 'ℹ️ Column contentPlan already exists, skipping creation';
    END IF;
END $$;

-- Step 2: Add index if it doesn't exist
CREATE INDEX IF NOT EXISTS "Project_contentPlan_idx" 
ON "Project" USING gin ("contentPlan");

RAISE NOTICE '✅ Index Project_contentPlan_idx created/verified';

-- Step 3: Add comment
COMMENT ON COLUMN "Project"."contentPlan" 
IS 'Array of content plan topics generated by AI. Each topic has: title, description, keywords, priority';

-- Step 4: Verify column exists and is properly configured
DO $$
DECLARE
    col_exists boolean;
    col_type text;
    col_default text;
BEGIN
    SELECT 
        EXISTS (
            SELECT 1 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
              AND table_name = 'Project' 
              AND column_name = 'contentPlan'
        ),
        data_type,
        column_default
    INTO col_exists, col_type, col_default
    FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'Project' 
      AND column_name = 'contentPlan';
    
    IF col_exists THEN
        RAISE NOTICE '✅ SUCCESS: contentPlan column exists and is ready to use';
        RAISE NOTICE '   - Data Type: %', col_type;
        RAISE NOTICE '   - Default: %', col_default;
    ELSE
        RAISE EXCEPTION '❌ ERROR: contentPlan column was not created';
    END IF;
END $$;

-- Step 5: Test insert/update capability
DO $$
DECLARE
    test_project_id text;
    update_success boolean := false;
BEGIN
    -- Get first project ID for testing
    SELECT id INTO test_project_id FROM "Project" LIMIT 1;
    
    IF test_project_id IS NOT NULL THEN
        -- Test update
        UPDATE "Project" 
        SET "contentPlan" = '[{"title":"Migration Test","description":"Testing contentPlan column","keywords":"test","priority":"high"}]'::jsonb
        WHERE id = test_project_id;
        
        -- Verify update worked
        SELECT 
            CASE 
                WHEN "contentPlan" IS NOT NULL THEN true 
                ELSE false 
            END
        INTO update_success
        FROM "Project"
        WHERE id = test_project_id;
        
        IF update_success THEN
            RAISE NOTICE '✅ Test update successful for project: %', test_project_id;
            
            -- Rollback test data
            UPDATE "Project" 
            SET "contentPlan" = '[]'::jsonb
            WHERE id = test_project_id;
            
            RAISE NOTICE '✅ Test data cleaned up';
        ELSE
            RAISE WARNING '⚠️ Test update failed verification';
        END IF;
    ELSE
        RAISE NOTICE 'ℹ️ No projects found for testing (empty database)';
    END IF;
END $$;

-- Final verification query
SELECT 
    'contentPlan' as column_name,
    data_type,
    column_default,
    is_nullable,
    '✅ Column is ready for use!' as status
FROM information_schema.columns 
WHERE table_schema = 'public' 
  AND table_name = 'Project' 
  AND column_name = 'contentPlan';

-- Success message
DO $$
BEGIN
    RAISE NOTICE '═══════════════════════════════════════════════════════';
    RAISE NOTICE '✅ MIGRATION COMPLETE: contentPlan column is ready!';
    RAISE NOTICE '═══════════════════════════════════════════════════════';
END $$;
